[package]
name = "sol-hunter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
futures-util = "0.3.33"

serde = { version = "1.0.229", features = ["derive", "serde_derive"] }
serde_json = "1.0.151"

wincode = "=0.5.5"
solana-client = "=4.0.0"
solana-sdk = "=4.0.0"
pump-rust-client = { version = "0.1.9", default-features = false }

tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
tokio-tungstenite = { version = "0.30.0", features = ["native-tls"] }
log = "0.4.33"
env_logger = "0.11.11"
