[package]
name = "sol-hunter"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "sync", "fs", "io-std"] }
tokio-tungstenite = { version = "0.30.0", features = ["native-tls"] }
futures-util = "0.3.33"
anyhow = "1.0.104"

serde = { version = "1.0.229", features = ["derive", "serde_derive"] }
serde_json = "1.0.151"
csv = "1.4.0"

log = "0.4.33"
env_logger = "0.11.11"
async-trait = "0.1.91"

rust_decimal = { version = "1.42.1", features = ["macros"] }
chrono = { version = "0.4.45", features = ["serde"] }
helius = "1.1.0"
